services:
  tailscale-changedetection:
    image: tailscale/tailscale
    container_name: tailscale-changedetection
    hostname: changedetection
    extends:
      file: ../tailscale.yml
      service: tailscale
    environment:
      - TS_SERVE_CONFIG=/config/changedetection.json
    expose:
      - 5000
    volumes:
      - ./tailscale:/config
      - tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    networks:
      - changedetection
      - uptime-kuma
    restart: unless-stopped

  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    volumes:
      - "./config:/config"
    environment:
      BASE_URL: https://changedetection.tail5916dc.ts.net
      PLAYWRIGHT_DRIVER_URL: ws://playwright:3000
      PUID: 1000
      GUID: 1000
      TZ: Europe/Paris
    depends_on:
      sockpuppetbrowser:
        condition: service_started
    restart: unless-stopped
    network_mode: service:tailscale-changedetection

  sockpuppetbrowser:
    hostname: playwright
    image: dgtlmoon/sockpuppetbrowser:latest
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    environment:
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1024
      SCREEN_DEPTH: 16
      MAX_CONCURRENT_CHROME_PROCESSES: 10
    networks:
      - changedetection

volumes:
  tailscale:

networks:
  changedetection:
    name: changedetection
  uptime-kuma:
    external: true
