services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    extends:
      file: ../common.yml
      service: common
    environment:
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=https://push.ryanmalonzo.fr
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=${WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN}
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=jNY6Ntnrxywushqrtv1ybYcK12zBdnwN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homepage
      - uptime-kuma
    restart: unless-stopped

networks:
  homepage:
    external: true
  uptime-kuma:
    external: true
