services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: linkwarden
    volumes:
      - ./data:/data/data
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    expose:
      - 3000
    networks:
      - linkwarden
      - proxy
      - uptime-kuma
    restart: unless-stopped
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkwarden.rule=Host(`bookmarks.ryanmalonzo.fr`)"
      - "traefik.http.routers.linkwarden.entrypoints=websecure"
      - "traefik.http.routers.linkwarden.tls.certresolver=cloudflare"
      - "traefik.http.services.linkwarden.loadbalancer.server.port=3000"
      - "traefik.http.routers.linkwarden.middlewares=robots@file,crowdsec@file"

  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - linkwarden

networks:
  linkwarden:
  proxy:
    external: true
  uptime-kuma:
    external: true
